In [9]:
import pandas as pd

# Ajuste o caminho para o seu arquivo real
caminho_arquivo = '../data/raw/teste.csv' 

df = pd.read_csv(caminho_arquivo)

# Ver as primeiras linhas
df.head()

             timestamp   value
0  2024-01-01 00:00:00  106.49
1  2024-01-01 00:59:59  107.61
2  2024-01-01 01:59:59  110.56
3  2024-01-01 02:59:59  111.55
4  2024-01-01 03:59:59  113.47

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  100 non-null    str
 1   value      100 non-null    float64
dtypes: float64(1), str(1)
memory usage: 1.7 KB

In [11]:
# Ver as primeiras linhas
df.head()

             timestamp   value
0  2024-01-01 00:00:00  106.49
1  2024-01-01 00:59:59  107.61
2  2024-01-01 01:59:59  110.56
3  2024-01-01 02:59:59  111.55
4  2024-01-01 03:59:59  113.47